local camera = require("src.core.camera")

describe("camera", function()
  it("centers the target when it is away from the edges", function()
    local c = camera.new(960, 540, 480, 270)
    camera.follow(c, { x = 480, y = 270 })
    assert.are.equal(240, c.x)
    assert.are.equal(135, c.y)
  end)

  it("clamps at the top-left corner", function()
    local c = camera.new(960, 540, 480, 270)
    camera.follow(c, { x = 0, y = 0 })
    assert.are.equal(0, c.x)
    assert.are.equal(0, c.y)
  end)

  it("clamps at the bottom-right corner", function()
    local c = camera.new(960, 540, 480, 270)
    camera.follow(c, { x = 960, y = 540 })
    assert.are.equal(480, c.x)
    assert.are.equal(270, c.y)
  end)
end)