local player = require("src.core.player")
local vec2   = require("src.core.vec2")

describe("player.update", function()
  it("does not move without input", function()
    local p = player.new({ x = 50, y = 50, speed = 100 })
    player.update(p, {}, 1)
    assert.are.equal(50, p.position.x)
    assert.are.equal(50, p.position.y)
  end)

  it("moves right at speed * dt", function()
    local p = player.new({ x = 0, y = 0, speed = 100 })
    player.update(p, { right = true }, 1)
    assert.are.near(100, p.position.x, 0.0001)
    assert.are.equal(0, p.position.y)
  end)

  it("moves diagonally at the same total speed", function()
    local p = player.new({ x = 0, y = 0, speed = 100 })
    player.update(p, { up = true, right = true }, 1)
    local dist = vec2.length(p.position)
    assert.are.near(100, dist, 0.01)
  end)

  it("clamps the player inside its bounds", function()
    local p = player.new({ x = 0, y = 0, size = 20, speed = 100 })
    player.update(p, { up = true, left = true }, 1,
      { minX = 0, minY = 0, maxX = 100, maxY = 100 })
    assert.are.near(10, p.position.x, 0.0001)
    assert.are.near(10, p.position.y, 0.0001)
  end)
end)

describe("player.take_damage", function()
  it("reduces hp and only reports death at zero", function()
    local p = player.new({ hp = 3 })
    assert.is_false(player.take_damage(p, 1))
    assert.is_false(player.take_damage(p, 1))
    assert.is_true(player.take_damage(p, 1))
    assert.are.equal(0, p.hp)
  end)
end)