-- Cowboy sprite data (ASCII maps + palette key mapping).
-- Source of truth for the cowboy's look; the build tool (scripts/gen_sprites.lua)
-- bakes these maps into a spritesheet + atlas. Keys refer to src/core/palette.lua.

return {
  palette = {
    H = "hat", h = "hat_dark",
    F = "skin", f = "skin_dark",
    E = "eye",
    B = "bandana", b = "bandana_dark",
    T = "denim", t = "denim_dark",
    S = "shirt", s = "shirt_dark",
    L = "denim_dark",
    G = "gun",
    O = "boot",
  },

  sets = {
    idle = {
      fps = 4,
      frames = {
        {
          "....HHHH....",
          "...HHHHHH...",
          "..HHHHHHHH..",
          "..hhhhhhhh..",
          "....FEEF....",
          "....Ff.Ff...",
          "....bBBb....",
          "...BBBBBB...",
          "..TSssSST...",
          "..TSSSSSST..",
          "..ttTTTTtt..",
          "...L..LL....",
          "...O..OO....",
        },
        {
          "....HHHH....",
          "...HHHHHH...",
          "..HHHHHHHH..",
          "..hhhhhhhh..",
          "....FEEF....",
          "....Ff.Ff...",
          "....bBBb....",
          "...BBBBBB...",
          "..TSss..ST..",
          "..TSSSSSST..",
          "..ttTTTTtt..",
          "...L..LL....",
          "...O..OO....",
        },
      },
    },
    walk = {
      fps = 8,
      frames = {
        {
          "....HHHH....",
          "...HHHHHH...",
          "..HHHHHHHH..",
          "..hhhhhhhh..",
          "....FEEF....",
          "....Ff.Ff...",
          "....bBBb....",
          "...BBBBBB...",
          "..TSssSST...",
          "..TSSSSSST..",
          "..ttTTTTtt..",
          "..L....L....",
          ".O......O...",
        },
        {
          "....HHHH....",
          "...HHHHHH...",
          "..HHHHHHHH..",
          "..hhhhhhhh..",
          "....FEEF....",
          "....Ff.Ff...",
          "....bBBb....",
          "...BBBBBB...",
          "..TSssSST...",
          "..TSSSSSST..",
          "..ttTTTTtt..",
          ".L......L...",
          "O........O..",
        },
        {
          "....HHHH....",
          "...HHHHHH...",
          "..HHHHHHHH..",
          "..hhhhhhhh..",
          "....FEEF....",
          "....Ff.Ff...",
          "....bBBb....",
          "...BBBBBB...",
          "..TSssSST...",
          "..TSSSSSST..",
          "..ttTTTTtt..",
          "...L..L.....",
          "...O..O.....",
        },
        {
          "....HHHH....",
          "...HHHHHH...",
          "..HHHHHHHH..",
          "..hhhhhhhh..",
          "....FEEF....",
          "....Ff.Ff...",
          "....bBBb....",
          "...BBBBBB...",
          "..TSssSST...",
          "..TSSSSSST..",
          "..ttTTTTtt..",
          "....L....L..",
          "....O....O..",
        },
      },
    },
    shoot = {
      fps = 24,
      frames = {
        {
          "....HHHH....",
          "...HHHHHH...",
          "..HHHHHHHH..",
          "..hhhhhhhh..",
          "....FEEF....",
          "....Ff.Ff...",
          "....bBBb....",
          "...BBBBBB...",
          "..TSsG.SST..",
          "..TSSSSSST..",
          "..ttTTTTtt..",
          "...L....L...",
          "...O....O...",
        },
        {
          "....HHHH....",
          "...HHHHHH...",
          "..HHHHHHHH..",
          "..hhhhhhhh..",
          "....FEEF....",
          "....Ff.Ff...",
          "....bBBb....",
          "...BBBBBB...",
          "..TSG..SST..",
          "..TSSSSSST..",
          "..ttTTTTtt..",
          "...L....L...",
          "...O....O...",
        },
      },
    },
  },
}