-- Hero sprite data (title screen box-art portrait).
--
-- Authored by hand as scanline spans and baked to ASCII: the bust is 80x100
-- and gets drawn at scale 2 (160x200 on the 480x270 canvas), the revolver is
-- a separate 40x46 sprite so it can cock and kick without redrawing the body.
--
-- Pose: back to the menu on the diagonal, head turned away so the face reads
-- in near silhouette against the sunset with one eye burning, revolver up on
-- the menu side without him looking at it.
--
-- `shade = "flat"` -- every tone is chosen by hand through explicit light and
-- dark palette keys, so the build tool must not re-shade it.
--
-- Sets:
--   body - 1 frame, the bust; drawn once, bobbed by the caller
--   idle - 2 frames, revolver at rest (1px of breathing)
--   draw - 2 frames, hammer cocked then the recoil kick
--
-- Keys refer to src/core/palette.lua. Baked by scripts/gen_sprites.

return {
  shade = "flat",

  palette = {
    G = "hat_light", H = "hat", h = "hat_dark", j = "hat_deep",
    k = "leather_dark", Y = "gold", F = "skin", f = "skin_dark",
    d = "skin_deep", u = "stubble", E = "eye_glow", R = "bandana",
    r = "bandana_dark", V = "vest", v = "vest_dark", C = "leather",
    c = "leather_dark", W = "belt", M = "gun", m = "gun_dark", N = "steel",
    n = "steel_light", B = "rim_cool", A = "rim_warm"
  },

  sets = {
    body = {
      fps = 1,
      frames = {
        {
          "................................................................................",
          "................................................................................",
          "......................................BhhhHHHHGGGA..............................",
          ".....................................BhhhHHHHHHGGGA.............................",
          "....................................BhhhHHHHHHHHGGGA............................",
          "...................................BhhhHHHHHHHHHGGGA............................",
          "...................................BhhhHHhhhHHHHHGGGA...........................",
          "..................................BhhhHHHhhhHHHHHGGGA...........................",
          "..................................BhhhHHHhhhHHHHHHGGGA..........................",
          "..................................BhhhHHHhhhHGGGHHGGGA..........................",
          ".................................BhhhHHHHhhhHGGGHHGGGA..........................",
          ".................................BhhhHHHHhhhHGGGHHHGGGA.........................",
          ".................................BhhhHHHHhhhHGGGHHHGGGA.........................",
          "................................BhhhHHHHHhhhHGGGHHHGGGA.........................",
          "................................BhhhHHHHHhhhHGGGHHHHGGGA........................",
          "................................BhhhHHHHHhhhHGGGHHHHGGGA........................",
          "................................BhhhHHHHHHhhhHHHHHHHGGGA........................",
          "...............................BhhhHHHHHHHHHHHHHHHHHHGGGA.......................",
          "...............................BkkkkkkkkkkkkkkkkYYYYYYkkA.......................",
          "...............................BkkkkkkkkkkkkkkkkYYkkYYkkA.......................",
          "..............................BkkkkkkkkkkkkkkkkkYYYYYYkkkA......................",
          "....................BhhhhhhhhhhHHHHHHHHHHHHHHHHHHHHHGGGGGGGGGGGGA...............",
          "...............BhhhhhhhhhhhhhHHHHHHHHHHHHHHHHHHHHHHHHHGGGGGGGGGGGGGGA...........",
          "............BhhhhhhhhhhhhhhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGGGGGGGGGGGGGGA.........",
          "..........BhhhhhhhhhhhhhhHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGGGGGGGGGGGGGA........",
          ".........BjjjjjjjjjjjjjhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhHHHHHHHHHHHHA.......",
          "........BjjjjjjjjjjjjhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhHHHHHHHHHA........",
          "........BjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjhhhhhhhA..........",
          "........BjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjA.............",
          ".........BjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjA................",
          "...........BjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjA....................",
          "..............BjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjA........................",
          "..................BjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjA............................",
          ".......................BjjjjjjjjjjjjjjjjjjjjjjjA................................",
          "............................BjjjjjjjjjjjjjjjjjjjjjjjjjjjA.......................",
          "...............................BjjjjjjjjjjjjjjjjjjjjjjjjA.......................",
          "...............................BjjjjjjjjjjjjjjHHHHHHhhhhhA......................",
          "..............................BjjjjjjjjjjjjjjjHHHHHHhhhhhA......................",
          "..............................BjjjjjjjjjjjjjjjjHHHHHhhhhhA......................",
          "..............................BjjjjjjjjjjjjjjjjHHHHHHhhhhA......................",
          ".............................BjjjjjjjjjjjjjjjjjjHHHHHhhhhA......................",
          ".............................BjjjjjjjjjjjjjjjjjjhhhhhhhhhA......................",
          "............................BdEEEEEEjjjjjjjjjjjjjjjhhhhhhA......................",
          "............................BdEnnnnEjjjjjjjjjjjjjjjhhhhhhA......................",
          ".............................BjjjjjjjjjjjjjjjjjjjjjhhhhhhA......................",
          ".............................BdddddddjjjjjjjjjjjjjhhhhhhA.......................",
          "..............................BdddddddjjjjjjjjjjjjhhhhhhA.......................",
          "..............................BddddddddjjjjjjjjjjjhhhhhhA.......................",
          "..............................Buuuuuuuujjjjjjjjjjhhhhhhh....dddddddddA..........",
          "...............................Buuuuuuujjjjjjjjjjhhhhhhh...dddddddfffffA........",
          "...............................Buuuuuuujjjjjjjjjhhhhhhh...dddjddjffffFFFA.......",
          "................................Buuuuuujjjjjjjjjhhhhhh....dddjdfjffjffFFFA......",
          ".................................Bjjjjjjjjjjjjjhhhhhhh....dddjdfjffjffFFFA......",
          "..................................Bjjjjjjjjjjjjhhhhhh.....dddjddjffffFFFFA......",
          "................................BRRjjjjjjjjjjjjjjjjr.......ddddddfffffffA.......",
          "..............................Brrrrrrjjjjjjjjjjjrrrrr.......dddddddddddA........",
          "............................BrrrrrrrRRRjjjjjjRrrrrrrr...CCCCCdddddddddA.........",
          "..........................BrrrrrrrrRRRRRRRRRRrrrrrrr...ccccccCCCCCCCCA..........",
          "........................BrrrrrrrrrRRRRRRRRRRRRRRRRR....ccccccCCCCCCCCA..........",
          "......................BrrrrrrrrrrRRRRRRRRRRRRRRRR.......ccccccccccccA...........",
          "....................BrrrrrrrrrrrRRRRRRRRRRRRRRGGGC......ccccccCCCCCCA...........",
          "..................BrrrrrrrrrrrrRRRRRRRRRRRRVVGGGGGGC...ccccccCCCCCCA............",
          "................BrrrrrrrrrrrrrRRRRRRRRRvvvvvvvvvvvvGCC.ccccccCCCCCCA............",
          "...............BrrrrrrrrrrrrrrrrrrrccccccccccccccccGGCccccccCCCCCCA.............",
          "..............BrrrrrrrrrrrrrrrrVVVVVVVVVVVVVVVVVVGGGGGccccccCCCCCCA.............",
          "..............BrrrrrrrrrrrrvvvvVVVVVVVVVVVVVVVVVVVGGGccccccCCCCCCA..............",
          "...............BrrrrrrrvvvvvvvVVVVvvvVVVVVVVVVVVVVVGGccccccCCCCCCA..............",
          "...............BvrrrrvvvvvvvvvVVVVvvvVVVVVVVVVVVVVVVccccccCCCCCCA...............",
          ".................BvvvvvvvvvvvVVVVVvvvvVVVVVVVVVVVVVVccccccCCCCCCA...............",
          ".................BvvvvvvvvvvvVVVVVVvvvVVVVVVVVVVVVVccccccCCCCCCA................",
          "................BvvvvvvvvvvvvVVVVVVvvvVVVVVVVVVVcccccccccCCCCCCA................",
          "................BvvvvvvvvvvvVVVVVVVvvvVVVVVVVVVVccccccccCCCCCCA.................",
          "................BvvvvvvvvvvvVVVVVVVvvvvVVVVVVVVVccccccccCCCCCCA.................",
          "...............BvvvvvvvvvvvvVVVVVVVVvvvVVVVVVVVcccVVVVCCCCCCA...................",
          "...............BvvvvvvvvvvvvVVVVVVVVvvvVVVVVVVVcccVVVVVCCCCCA...................",
          "...............BvvvvvvvvvvvvVVVVVVVVvvvVVVVVVVVcccVVVVVCCCCCA...................",
          "................BvvvvvvvvvvvVVVVVVVVvvvVVVVVVVVcccVVVVVCCCCCA...................",
          "................BvvvvvvvvvvvVVVVVVVVvvvvVVVVVVcccVVVVVCCCCCA....................",
          "................BvvvvvvvvvvvvVVVVVVVVvvvVVVVVVcccVVVVVCCCCCA....................",
          ".................BvvvvvvvvvvvVVVVVVVVvvvVVVVVVcccVVVVVCCCCCA....................",
          ".................BvvvvvvvvvvvVVVVVVVVvvvVVVVVVcccVVVVVCCCCA.....................",
          "..................BvvvvvvvvvvVVVVVVVVvvvVVVVVVVVVVVVVCCCCCA.....................",
          "..................BvvvvvvvvvvvVVVVVVVvvvvVVVVVVVVVVVVCCCCCA.....................",
          "...................BvvvvvvvvvvVVVVVVVVvvvVVVVVVVVVVVVCCCCA......................",
          "...................BvvvvvvvVvvVVVVVVVVvvvVVVVVVVVVVVCCCCCA......................",
          "....................BvvvvvvVvvVVVVVVVVvvvVVVVVVVVVVVCCCCCA......................",
          "....................BvvvvvvVvvvVVVVVVVvvvVVVVVVVVVVVCCCCA.......................",
          ".....................BvvvvvVvvvVVVVVVVvvvvVVVVVVVVVCCCCCA.......................",
          ".....................BvvvvvVVvvVVVVVVVVvvvVVVVVVVVVCCCCCA.......................",
          "......................BvvvvVVvvVVVVVVVVvvvVVVVVVVVVCCCCA........................",
          "......................BvvvvVVVVVVVVVVVVvvvVVVVVVVVCCCCCA........................",
          ".......................BvvvvVVVVVVVVVVVvvvVVVVVVVVCCCCCA........................",
          ".......................BvvvvWWWWWWWWWWWWWWWWWWWWWWWWWWA.........................",
          "........................WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.........................",
          "........................WWWWWWWWWYYYYYYYYYYYYYWWWWWWWWW.........................",
          "........................cccccccccYYYcccccccYYYccccccccc.........................",
          ".........................ccccccccYYYcccccccYYYccccccccc.........................",
          ".........................ccccccccYYYcccccccYYYcccccccc..........................",
          ".........................ccccccccYYYYYYYYYYYYYcccccccc..........................",
          "..........................cccccccccccjjjjjcccccccccccc..........................",
        },
      },
    },
    idle = {
      fps = 2,
      frames = {
        {
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          ".........................N..............",
          ".....................nnNNNN.............",
          "....................nnnnNjjN............",
          ".....................nnnNNjj............",
          ".....................nnMMNjjj...........",
          "...................NNMMMMMNjj...........",
          "..................NNMMMMMMNNNN..........",
          "................NNMMMMMMMmmNN...........",
          "...............NNMMMMMMMmmm.............",
          ".............NNMMMMMMMmmmm..............",
          "........mm..NNMMMMMMMmmmm...............",
          ".......mmmmNNMMMMMMmmmm.................",
          ".....MmmmmmmmMMMMMmmmm..................",
          "....NNMmmmmMmMMMmmmm....................",
          "..NNMMMMmMmMmmMmmmm.....................",
          ".MMMMMMMmmMmMmmMM.......................",
          "..MMMMMMMmMmmMmmMM......................",
          "..MMMnnMMMmMmMmmMM......................",
          "...M.nnnMMmmmmmMMMM.....................",
          "......nnMMMmmMMMMMMM....................",
          ".......MMMmmMMMMMMMM....................",
          ".......MMMMMMMMMMYYY....................",
          "........MMMMMMmmYjYYY...................",
          "........CMMMMMYmjjjYY...................",
          ".......CCCMMYYYmjjjYY...................",
          "......CCCcMMMYYjjjjY....................",
          ".....CCCCCcMcYYYjYY.....................",
          ".....CCCCCccccYYY.......................",
          "......CCccCccccY........................",
          ".......CcCCCccccc.......................",
          ".......CCCCcccccc.......................",
          "........CCCcCccccc......................",
          ".........CCCCcccccc.....................",
          "..........CCCCccccc.....................",
          "..........CCCCCccc......................",
          "...........CCCCC........................",
          "............CCC.........................",
        },
        {
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          ".........................N..............",
          ".....................nnNNNN.............",
          "....................nnnnNjjN............",
          ".....................nnnNNjj............",
          ".....................nnMMNjjj...........",
          "...................NNMMMMMNjj...........",
          "..................NNMMMMMMNNNN..........",
          "................NNMMMMMMMmmNN...........",
          "...............NNMMMMMMMmmm.............",
          ".............NNMMMMMMMmmmm..............",
          "........mm..NNMMMMMMMmmmm...............",
          ".......mmmmNNMMMMMMmmmm.................",
          ".....MmmmmmmmMMMMMmmmm..................",
          "....NNMmmmmMmMMMmmmm....................",
          "..NNMMMMmMmMmmMmmmm.....................",
          ".MMMMMMMmmMmMmmMM.......................",
          "..MMMMMMMmMmmMmmMM......................",
          "..MMMnnMMMmMmMmmMM......................",
          "...M.nnnMMmmmmmMMMM.....................",
          "......nnMMMmmMMMMMMM....................",
          ".......MMMmmMMMMMMMM....................",
          ".......MMMMMMMMMMYYY....................",
          "........MMMMMMmmYjYYY...................",
          "........CMMMMMYmjjjYY...................",
          ".......CCCMMYYYmjjjYY...................",
          "......CCCcMMMYYjjjjY....................",
          ".....CCCCCcMcYYYjYY.....................",
          ".....CCCCCccccYYY.......................",
          "......CCccCccccY........................",
          ".......CcCCCccccc.......................",
          ".......CCCCcccccc.......................",
          "........CCCcCccccc......................",
          ".........CCCCcccccc.....................",
          "..........CCCCccccc.....................",
          "..........CCCCCccc......................",
          "...........CCCCC........................",
          "............CCC.........................",
          "............C...........................",
        },
      },
    },
    draw = {
      fps = 10,
      frames = {
        {
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          ".....................NN.................",
          "...................nNNNN................",
          ".................nnnnNjjj...............",
          ".................nnnnNjjjN..............",
          "..................nnMMNjjj..............",
          ".................NNMMMMNNNN.............",
          "................NNMMMMMmNNN.............",
          "...............NNMMMMMmmmN..............",
          "..............NMMMMMMmmmm...............",
          ".............NNMMMMMmmmm................",
          "...........NNMMMMMMmmm..................",
          "..........NNMMMMMMmmm...................",
          "......mm.NNMMMMMMmmm....................",
          ".M...mmmmNMMMMMMmmm.....................",
          "nMM.mmmmmmmMMMMmmm......................",
          "MMMM.mmmmMmmMMm.m.......................",
          "MMMMMNmMMmMmmMMM........................",
          "MMMMMMMmMmmMmmmM........................",
          "MMMMMMMMmMmmMmmMM.......................",
          "MMMMnnMMMmMmmmMMMM......................",
          ".MMMnnnMMmmmmMMMMMM.....................",
          ".....nnMMMmmMMMMMYY.....................",
          "......MMMMMMMMMMYYYY....................",
          ".......MMMMMMMmYjjYYY...................",
          "........MMMMMMmmjjjYY...................",
          "........CMMMMYjmjjjYY...................",
          ".......CCCMMYYYjjjYY....................",
          "......CCCcMMMYYYjY......................",
          ".....CCCCCccccYYY.......................",
          "......CCCCcccccYC.......................",
          "......CCCccCccccc.......................",
          ".......CCcCCcccccc......................",
          "........CCCcccccccc.....................",
          ".........CCCCCcccccc....................",
          "..........CCCCcccccc....................",
          "...........CCCCCccc.....................",
          "............CCCCC.......................",
          ".............CCC........................",
          "..............C.........................",
          "........................................",
          "........................................",
        },
        {
          "........................................",
          "................NN......................",
          "................NNj.....................",
          "..............nnNNjj....................",
          ".............nnnnNjjjj..................",
          ".............nnnMMNjjNN.................",
          "..............nMMMMNNNN.................",
          ".............NNMMMMmNN..................",
          "............NNMMMMMmm...................",
          "...........NNMMMMMmmm...................",
          "...........NMMMMMmmm....................",
          "..........NMMMMMmmm.....................",
          ".........NNMMMMmmm......................",
          "........NNMMMMMmmm......................",
          "........NMMMMMmmm.......................",
          ".......NMMMMMmmm........................",
          "...mmmNNMMMMmmm.........................",
          "...mmmmmmMMmmm..........................",
          "..mmmmmMmmMMMM..........................",
          ".NMmmMmmMMmmmMM.........................",
          "NNMMMmmMmmMmmMMM........................",
          "NMMMMMmmMmmmMMMMMM......................",
          "MMMMMMMmmMmmMMMMMM......................",
          "MMMnnnMMmmmMMMMMYY......................",
          "MMMnnnMMMmMMMMMYYYYY....................",
          "....nnMMMMMMMmYjjjYYY...................",
          "......MMMMMMMYmmjjYY....................",
          ".......MMMMMMYjjjjY.....................",
          "........MMMMYYYjjY......................",
          ".......CCMMMMYYYYY......................",
          "......CCCccMccYYY.......................",
          "......CCCCcccccYc.......................",
          ".....CCCCCccccccccc.....................",
          "......CCCccCCccccccc....................",
          "........CCCCccccccccc...................",
          ".........CCCCCCcccccc...................",
          "..........CCCCCcCccc....................",
          "............CCCCCCc.....................",
          ".............CCCCC......................",
          "..............CCCC......................",
          "...............CC.......................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
          "........................................",
        },
      },
    },
  },
}
