-- Hero sprite data (title screen box-art portrait).
--
-- The bust is the box-art reference (scripts/ascii_output.txt), 56x64, drawn
-- at scale 2 (112x128 on the 480x270 canvas). idle/draw are the revolver, a
-- 40x46 sprite each, recovered from the baked sheet so cock and kick stay
-- aligned to the body through the shared gun origin (GUN_OX/GUN_OY).
--
-- `shade = "flat"` -- every tone is chosen explicitly through light and dark
-- palette keys, so the build tool must not re-shade it.
--
-- Sets:
--   body - 1 frame, the bust; drawn once, bobbed by the caller
--   idle - 2 frames, revolver at rest (1px of breathing)
--   draw - 2 frames, hammer cocked then the recoil kick
--
-- Keys refer to src/core/palette.lua. Baked by scripts/gen_sprites.

return {
  shade = "flat",

  palette = {
    G = "hat_light",
    H = "hat",
    h = "hat_dark",
    j = "hat_deep",
    k = "leather_dark",
    Y = "gold",
    F = "skin",
    f = "skin_dark",
    d = "skin_deep",
    u = "stubble",
    E = "eye_glow",
    R = "bandana",
    r = "bandana_dark",
    V = "vest",
    v = "vest_dark",
    C = "leather",
    c = "leather_dark",
    W = "belt",
    M = "gun",
    m = "gun_dark",
    N = "steel",
    n = "steel_light",
    B = "rim_cool",
    A = "rim_warm",
    S = "skin_light",
    s = "bandana_light",
  },

  sets = {

  body = {
    fps = 1,
    frames = {
      {
        "........................................................",
        "........................................................",
        ".........................GHhHGGGA.......................",
        ".......................hhhHjjGGGGGA.....................",
        ".....................GjjhhjjHHHHHGHA....................",
        "....................jjjjjhhjhhhHHHGGA...................",
        "....................jjjjjhhjhhhhHHHGG...................",
        "....................jjjjjhhjhhhhHHHGHA..................",
        "...................BjjjjhhhjhhhhhHHHHH..................",
        "...................BjjjjhjhjhhhhhhHHhkn.................",
        "...................jjjjjhjjjhhhkYYYYkkk.................",
        "............hHhhhHjjjjjjjjjjhjjjYkkYkkkA................",
        "......BhjjjjjjjjjjjjjjjjjjjjhjjjYYYjjjhHGGGA............",
        "....BjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjhhhhhhGGGA........",
        "...BjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjhhhGA......",
        "...BjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjhhA.....",
        "....jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjhh.....",
        ".....jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjHhA....",
        "......jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjh.....",
        ".........jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjA......",
        ".............jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjA........",
        "...............jjjjjjjjjjjjjjjjjjjjjjjjjA...............",
        "...............jjjjjjjjjjjjjjjjjjjjjjjjjA...............",
        "...............jjjjjjjjjjjjjjjjjjjjjjjjjA...............",
        "...............BjjjjjjjjjjjjjjjjjjEEEjjj................",
        "...............BjjjjjjjjjjjjjjjjjEnnnEfjA...............",
        "...............BjjjjjjjjjjjjjjjjjEEEEjjjjA..............",
        "...............Bdddddjjjjjjjjjjjjjjjjjjjjj..............",
        "................ddddddddddddddddddddjjjSA...............",
        "................ddddddddduuuuuufddddddd.................",
        "................ddddddddduSSSuuuuduuuufAj...............",
        ".................ddjdSFFFFFFFuuuuuuuufff................",
        ".................jddduuuuuuuuuuuuufuuuf..A..............",
        ".................vddduuuuuuuuuuuuuuuuff.G...............",
        "................jvjjFuuuuuuuuuuuuuuuuu.WfjA.............",
        "................jjjvjuuuuuuuuuuuuuuuukkkkCvG............",
        "................jjjjvuuuuuuuuudddduuu.kkkkkkGA..........",
        "...............vjjddjdddddddddddddddfSWWkkWWkA..........",
        "...............jjvvRRsRRddddsssssssRdS.WWkWWkC...A......",
        "...............jjvvRRRRRRRRdsssssrssRfVWWWWWkC..FFA.....",
        "..............BjjvjRRRRRRRRRRsRssssrRrVGCVYYFFfffFFA....",
        "..............jjjRRRRRRRRRRRRRssssssRrRVrkYYYuufffFFA...",
        "..............jRRRRRRRRRRRRRRRRssssrsRRkWvFfYYuffffFS...",
        ".............RRRRRRRRRRRRRRRRRRRRRRRrRhYkfffuYkufffFF...",
        "..........RRRRRRRRRRRRRRRRRRRRRRRRRRRRWYYYfruuuudrufS...",
        "........RRRRRRRRRRRRVRRRRRRRRRRRRRRRRCvhYnfffdddddurA...",
        ".......RRRRRRRRRRRVVVVRRRRRRRRRRRRRYYkVvvfkffddddudfA...",
        "......RRRRRRRRRRVVVVCVVCCCCCCCCCCCCCYYvvvffffddududFA...",
        ".....BRRRRRRRRRVGCVVkkkkkkkkkkkYkkkkkYhvvjffdududfuFW...",
        "....BRRRRRRRRRRCVVkkkvkkkkkWkkkYnYkkWWWkvjffdudddfujv...",
        "....RRRRRRRRRRVWWkkkvkkkkkkYkkkkYYWWvjCjvvVjCCVVjjjjjA..",
        "..BRRRRRRRRRGWWWWkkkkkkkkkkYYkWWvjjkjjjjjjjjjjjjjjjjvW..",
        "..RRRRRRRRRCWWWWWkkkkkkkkkkkYYvjCjjkjjjjjjjjjjjjjjjjvvA.",
        "....RRRRRGWWWWWWWkkkkkkYkWWjjYYkjjjjjjjjjjjjjjjjjjjjjvW.",
        "...VWCGRCWWWWWWWWkkkkWWYYYCjjjjkjjjjjjjjjjjjjjjjjjjjjvv.",
        "...VWWWWWWWWWWWWWkkWWvjjYYYjjjjjjjjjjjjjjjjjjjjjjjjjjvv.",
        "..VjWWWWWWWWWWWWhWvjYjjjjjYkjjjjjjjjjjjjjjjjjjjVjjjjjvv.",
        "..VjjvWWWWWWWhvjjCjjYnYjjjjjjjjjjjjjjjjjjjjjVVVVjjjjjvv.",
        "..jjjCvWWWWWvjCjjjjjjYnjjjjjjjjjjjjjjjjjjjVVVVVVjjjjjvv.",
        "..jjjjjjWvjjjjjjYYjjjjjkjjjjjkkkYYYYYWWWWWVVVVVVjjjjjvv.",
        "..jjjjjjjjjjjjjjYYYjvvjjjYYYYYYYYYYYYjjjjjjjjjjjjjjvvWW.",
        "..jjjjjjjjjvYvvvYYYvvjjjjYYkkkjjkkkYYjjjjjjjjjjjjjjvvWW.",
        "..jjjjjjjvvvYnvjjvYvkjjjjYYkkkjjkkkYYjjjjjjjjjjjjjjvvvW.",
        "..jjjjjjjjjjYYnYjvjYjjjjjYYYYYjjYYYYYjjjjjjjjjjjjjjjvvW.",
      },
    },
  },

  idle = {
    fps = 1,
    frames = {
      {
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".........................N..............",
        "....................BnnNNNN.............",
        "..................BnnnnnNjjN............",
        ".................BnnnnnnNjj.............",
        ".................BnnnnMNjjj.............",
        "................BnnMMMMNjj..............",
        "...............BNNMMMMMNNN..............",
        "..............BNNMMMMMMNNN..............",
        ".............BNNMMMMMMMmmN..............",
        "...........BNNMMMMMMMmmmm...............",
        "......mm..BNNMMMMMMMmmmm................",
        ".....mmmmBNNMMMMMMmmmm..................",
        "...MmmmmmmmMMMMMmmmm....................",
        "..NNMmmmmMmMMMmmmm......................",
        ".NNMMMMmMmMmmMmmmm......................",
        "MMMMMMMmmMmMmmMM........................",
        ".MMMMMMMmMmmMmmMM.......................",
        ".MMMnnMMMmMmMmmMM.......................",
        "..M.nnnMMmmmmmMMMM......................",
        "....nnMMMmmMMMMMMM......................",
        ".....MMMmmMMMMMMMM......................",
        ".....MMMMMMMMMMYYY......................",
        "......MMMMMMmmYjYYY.....................",
        "......CMMMMMYmjjjYY.....................",
        ".....CCCMMYYYmjjjYY.....................",
        "....CCCkMMMYYjjjjY......................",
        "...CCCCCkMkYYYjYY.......................",
        "...CCCCCkkkkYYY.........................",
        "....CCkkCkkkkY..........................",
        ".....CkCCCkkkkk.........................",
        ".....CCCCkkkkkk.........................",
        "......CCCkCkkkkk........................",
        ".......CCCCkkkkkk.......................",
        "........CCCCkkkkk.......................",
        "........CCCCCkkk........................",
        ".........CCCCC..........................",
        "..........CCC...........................",
      },
      {
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        ".........................N..............",
        "....................BnnNNNN.............",
        "..................BnnnnnNjjN............",
        ".................BnnnnnnNjj.............",
        ".................BnnnnMNjjj.............",
        "................BnnMMMMNjj..............",
        "...............BNNMMMMMNNN..............",
        "..............BNNMMMMMMNNN..............",
        ".............BNNMMMMMMMmmN..............",
        "...........BNNMMMMMMMmmmm...............",
        "......mm..BNNMMMMMMMmmmm................",
        ".....mmmmBNNMMMMMMmmmm..................",
        "...MmmmmmmmMMMMMmmmm....................",
        "..NNMmmmmMmMMMmmmm......................",
        ".NNMMMMmMmMmmMmmmm......................",
        "MMMMMMMmmMmMmmMM........................",
        ".MMMMMMMmMmmMmmMM.......................",
        ".MMMnnMMMmMmMmmMM.......................",
        "..M.nnnMMmmmmmMMMM......................",
        "....nnMMMmmMMMMMMM......................",
        ".....MMMmmMMMMMMMM......................",
        ".....MMMMMMMMMMYYY......................",
        "......MMMMMMmmYjYYY.....................",
        "......CMMMMMYmjjjYY.....................",
        ".....CCCMMYYYmjjjYY.....................",
        "....CCCkMMMYYjjjjY......................",
        "...CCCCCkMkYYYjYY.......................",
        "...CCCCCkkkkYYY.........................",
        "....CCkkCkkkkY..........................",
        ".....CkCCCkkkkk.........................",
        ".....CCCCkkkkkk.........................",
        "......CCCkCkkkkk........................",
        ".......CCCCkkkkkk.......................",
        "........CCCCkkkkk.......................",
        "........CCCCCkkk........................",
        ".........CCCCC..........................",
        "..........CCC...........................",
        "..........C.............................",
      },
    },
  },

  draw = {
    fps = 1,
    frames = {
      {
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "..................BNN...................",
        "................BnnNN...................",
        "..............BnnnnNjj..................",
        "..............BnnnnNjjj.................",
        "..............BnnnMNjjj.................",
        ".............BnnMMMMNNN.................",
        "............BNNMMMMMMNN.................",
        "...........BNNMMMMMMMmN.................",
        "..........BNMMMMMMmmmm..................",
        ".........BNNMMMMMmmmm...................",
        ".......BNNMMMMMMmmm.....................",
        "......BNNMMMMMMmmm......................",
        "...mm.BNNMMMMMMmmm......................",
        ".M..mmmmNMMMMMMmmm......................",
        "nMM.mmmmmmMMMMmmm.......................",
        "MMMM.mmmmMmmMMm.........................",
        "MMMMMNmMMmMmmMMM........................",
        "MMMMMMMmMmmMmmmM........................",
        "MMMMMMMMmMmmMmmMM.......................",
        "MMMMnnMMMmMmmmMMMM......................",
        ".MMMnnnMMmmmmMMMMMM.....................",
        "....nnMMMmmMMMMMYY......................",
        ".....MMMMMMMMMMYYYY.....................",
        "......MMMMMMMmYjjYYY....................",
        ".......MMMMMMmmjjjYY....................",
        ".......CMMMMYjmjjjYY....................",
        "......CCCMMYYYjjjYY.....................",
        ".....CCCkMMMYYYjY.......................",
        "....CCCCCkkkkYYY........................",
        ".....CCCCkkkkkYC........................",
        ".....CCCkkCkkkkk........................",
        "......CCkCCkkkkkk.......................",
        ".......CCCkkkkkkkk......................",
        "........CCCCCkkkkkk.....................",
        ".........CCCCkkkkkk.....................",
        "..........CCCCCkkk......................",
        "...........CCCCC........................",
        "............CCC.........................",
        ".............C..........................",
        "........................................",
        "........................................",
      },
      {
        "........................................",
        "..............NN........................",
        "..............NN........................",
        "...........nnNNjj.......................",
        "..........nnnnNjjj......................",
        "..........nnnMMNjjN.....................",
        "...........nMMMMNNN.....................",
        "..........NNMMMMmNN.....................",
        ".........NNMMMMMmm......................",
        "........NNMMMMMmmm......................",
        "........NMMMMMmmm.......................",
        ".......NMMMMMmmm........................",
        "......NNMMMMmmm.........................",
        ".....NNMMMMMmmm.........................",
        ".....NMMMMMmmm..........................",
        "....NMMMMMmmm...........................",
        ".mmmNNMMMMmmm...........................",
        ".mmmmmmmMMmmm...........................",
        "mmmmmmMmmMMMM...........................",
        "NMmmMmmMMmmmMM..........................",
        "NNMMMmmMmmMmmMMM........................",
        "NMMMMMmmMmmmMMMMMM......................",
        "MMMMMMMmmMmmMMMMMM......................",
        "MMMnnnMMmmmMMMMMYY......................",
        "MMMnnnMMMmMMMMMYYYYY....................",
        "...nnMMMMMMMmYjjjYYY....................",
        ".....MMMMMMMYmmjjYY.....................",
        "......MMMMMMYjjjjY......................",
        ".......MMMMYYYjjY.......................",
        "......CCMMMMYYYYY.......................",
        ".....CCCkkMkkYYY........................",
        ".....CCCCkkkkkYk........................",
        "....CCCCCkkkkkkkkk......................",
        ".....CCCkkCCkkkkkkk.....................",
        ".......CCCCkkkkkkkkk....................",
        "........CCCCCCkkkkkk....................",
        ".........CCCCCkCkkk.....................",
        "...........CCCCCCk......................",
        "............CCCCC.......................",
        ".............CCCC.......................",
        "..............CC........................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
        "........................................",
      },
    },
  },
  },
}
