-- Hero sprite data (title screen).
--
-- A large, hand-shaded cowboy used only by the main menu. Unlike the in-game
-- sprites (12x13, auto-shaded from a light direction), this one is 30x38 and
-- authored with explicit light/dark palette keys, so `shade = "flat"` tells
-- the build tool to use each key's base color verbatim.
--
-- Sets:
--   idle - 2 frames, the head block breathes down 1px
--   draw - 2 frames, revolver raised then kicked up by the recoil
--
-- Keys refer to src/core/palette.lua. Baked by scripts/gen_sprites.

return {
  shade = "flat",

  palette = {
    G = "hat_light", H = "hat", h = "hat_dark",
    k = "leather_dark",
    F = "skin", f = "skin_dark",
    E = "eye_glow",
    R = "bandana", r = "bandana_dark",
    S = "shirt", s = "shirt_dark",
    C = "leather", c = "leather_dark",
    W = "belt", Y = "gold",
    T = "denim", t = "denim_dark",
    O = "boot", o = "boot_dark",
    M = "gun", m = "gun_dark", N = "steel",
  },

  sets = {
    idle = {
      fps = 2,
      frames = {
        {
          "..............................",
          "............GGGHHH............",
          "...........GGGGHHHH...........",
          "..........GGGGHHHHhh..........",
          "..........GGGHHHHHhh..........",
          "..........kkkkkkkkkk..........",
          "......HHHHHHHHHHhhhhhhhh......",
          "....HHHHHHHHHHHhhhhhhhhhhh....",
          "....hhhhhhhhhhhhhhhhhhhhhh....",
          "..........ffffffffff..........",
          "..........ffEEffEEff..........",
          "..........ffffffffff..........",
          "..........fFFFFFFFFf..........",
          ".........rRRRRRRRRRRr.........",
          ".........rRRRRRRRRRRr.........",
          "..........rrRRRRRRrr..........",
          ".....SSSCCCCCCCCCCCCCCsss.....",
          ".....SSSCCCSSSSSSSScccsss.....",
          ".....SSSCCCSSSSSSSScccsss.....",
          ".....SSSCYCSSSSSSSScccsss.....",
          ".....SSSCCCSSSSSSSScccsss.....",
          ".....SSSCCCSSSSSSSScccsss.....",
          ".....SSSCCCSSSSSSSScccsss.....",
          ".....SSSWWWWWWYYWWWWWWsss.....",
          ".....FFFTTTTTTTTTTTTTTfff.....",
          "....NMMmttTTTTTTTTTTttfff.....",
          "....MMm..ttTTTTTTTTtt.........",
          ".........ttTTTTTTTTtt.........",
          "........tttTTTTTTTTttt........",
          ".........tTTTt..tTTTt.........",
          ".........tTTTt..tTTTt.........",
          ".........tTTTt..tTTTt.........",
          ".........tTTTt..tTTTt.........",
          ".........OOOOO..OOOOO.........",
          ".........OOOOO..OOOOO.........",
          "........OOOOOO..OOOOOO........",
          "........oooooo..oooooo........",
          "..............................",
        },
        {
          "..............................",
          "..............................",
          "............GGGHHH............",
          "...........GGGGHHHH...........",
          "..........GGGGHHHHhh..........",
          "..........GGGHHHHHhh..........",
          "..........kkkkkkkkkk..........",
          "......HHHHHHHHHHhhhhhhhh......",
          "....HHHHHHHHHHHhhhhhhhhhhh....",
          "....hhhhhhhhhhhhhhhhhhhhhh....",
          "..........ffffffffff..........",
          "..........ffEEffEEff..........",
          "..........ffffffffff..........",
          "..........fFFFFFFFFf..........",
          ".........rRRRRRRRRRRr.........",
          ".........rRRRRRRRRRRr.........",
          ".....SSSCCCCCCCCCCCCCCsss.....",
          ".....SSSCCCSSSSSSSScccsss.....",
          ".....SSSCCCSSSSSSSScccsss.....",
          ".....SSSCYCSSSSSSSScccsss.....",
          ".....SSSCCCSSSSSSSScccsss.....",
          ".....SSSCCCSSSSSSSScccsss.....",
          ".....SSSCCCSSSSSSSScccsss.....",
          ".....SSSWWWWWWYYWWWWWWsss.....",
          ".....FFFTTTTTTTTTTTTTTfff.....",
          "....NMMmttTTTTTTTTTTttfff.....",
          "....MMm..ttTTTTTTTTtt.........",
          ".........ttTTTTTTTTtt.........",
          "........tttTTTTTTTTttt........",
          ".........tTTTt..tTTTt.........",
          ".........tTTTt..tTTTt.........",
          ".........tTTTt..tTTTt.........",
          ".........tTTTt..tTTTt.........",
          ".........OOOOO..OOOOO.........",
          ".........OOOOO..OOOOO.........",
          "........OOOOOO..OOOOOO........",
          "........oooooo..oooooo........",
          "..............................",
        },
      },
    },
    draw = {
      fps = 10,
      frames = {
        {
          "..............................",
          "............GGGHHH............",
          "...........GGGGHHHH...........",
          "..........GGGGHHHHhh..........",
          "..........GGGHHHHHhh..........",
          "..........kkkkkkkkkk..........",
          "......HHHHHHHHHHhhhhhhhh......",
          "....HHHHHHHHHHHhhhhhhhhhhh....",
          "....hhhhhhhhhhhhhhhhhhhhhh....",
          "..........ffffffffff..........",
          "..........ffEEffEEff..........",
          "..........ffffffffff..........",
          "..........fFFFFFFFFf..........",
          ".........rRRRRRRRRRRr.........",
          ".........rRRRRRRRRRRr.........",
          "..........rrRRRRRRrr..........",
          ".....SSSCCCCCCCCCCCCCCsss.....",
          ".....SSSCCCSSSSSSSScccsss.....",
          ".....SSSCCCSSSSSSSScccsss.....",
          "NNMMMFFFCYCSSSSSSSScccsss.....",
          "...mmFFFCCCSSSSSSSScccsss.....",
          ".....sssCCCSSSSSSSScccsss.....",
          "........CCCSSSSSSSScccsss.....",
          "........WWWWWWYYWWWWWWsss.....",
          "........TTTTTTTTTTTTTTfff.....",
          "........ttTTTTTTTTTTttfff.....",
          ".........ttTTTTTTTTtt.........",
          ".........ttTTTTTTTTtt.........",
          "........tttTTTTTTTTttt........",
          ".........tTTTt..tTTTt.........",
          ".........tTTTt..tTTTt.........",
          ".........tTTTt..tTTTt.........",
          ".........tTTTt..tTTTt.........",
          ".........OOOOO..OOOOO.........",
          ".........OOOOO..OOOOO.........",
          "........OOOOOO..OOOOOO........",
          "........oooooo..oooooo........",
          "..............................",
        },
        {
          "..............................",
          "............GGGHHH............",
          "...........GGGGHHHH...........",
          "..........GGGGHHHHhh..........",
          "..........GGGHHHHHhh..........",
          "..........kkkkkkkkkk..........",
          "......HHHHHHHHHHhhhhhhhh......",
          "....HHHHHHHHHHHhhhhhhhhhhh....",
          "....hhhhhhhhhhhhhhhhhhhhhh....",
          "..........ffffffffff..........",
          "..........ffEEffEEff..........",
          "..........ffffffffff..........",
          "..........fFFFFFFFFf..........",
          ".........rRRRRRRRRRRr.........",
          ".........rRRRRRRRRRRr.........",
          "..........rrRRRRRRrr..........",
          ".....SSSCCCCCCCCCCCCCCsss.....",
          ".....SSSCCCSSSSSSSScccsss.....",
          "NNMMMFFFCCCSSSSSSSScccsss.....",
          "...mmFFFCYCSSSSSSSScccsss.....",
          ".....sssCCCSSSSSSSScccsss.....",
          "........CCCSSSSSSSScccsss.....",
          "........CCCSSSSSSSScccsss.....",
          "........WWWWWWYYWWWWWWsss.....",
          "........TTTTTTTTTTTTTTfff.....",
          "........ttTTTTTTTTTTttfff.....",
          ".........ttTTTTTTTTtt.........",
          ".........ttTTTTTTTTtt.........",
          "........tttTTTTTTTTttt........",
          ".........tTTTt..tTTTt.........",
          ".........tTTTt..tTTTt.........",
          ".........tTTTt..tTTTt.........",
          ".........tTTTt..tTTTt.........",
          ".........OOOOO..OOOOO.........",
          ".........OOOOO..OOOOO.........",
          "........OOOOOO..OOOOOO........",
          "........oooooo..oooooo........",
          "..............................",
        },
      },
    },
  },
}
