-- Zombie sprite data (ASCII maps + palette key mapping).
-- Source of truth for the zombie look; baked into spritesheet + atlas by the
-- build tool. Keys refer to src/core/palette.lua.

return {
  palette = {
    Z = "zombie", z = "zombie_light",
    E = "eye",
    M = "mouth",
    R = "zombie_dark", D = "zombie_dark", C = "zombie_dark",
  },

  sets = {
    walk = {
      fps = 5,
      frames = {
        {
          "....ZZZZ....",
          "...ZZZZZZ...",
          "..ZZZZZZZZ..",
          "..zZEEZz....",
          "..zZEEZz....",
          "..M....M....",
          "..RRRRRRRR..",
          ".CR......RC.",
          ".CZ......ZC.",
          "..ZZZZZZZZ..",
          "...CC..CC...",
          "..DD....DD..",
          "............",
        },
        {
          "....ZZZZ....",
          "...ZZZZZZ...",
          "..ZZZZZZZZ..",
          "..zZEEZz....",
          "..zZEEZz....",
          "..M....M....",
          "..RRRRRRRR..",
          ".R........R.",
          ".Z........Z.",
          "..ZZZZZZZZ..",
          "..CC..CC....",
          "..DD....DD..",
          "............",
        },
        {
          "....ZZZZ....",
          "...ZZZZZZ...",
          "..ZZZZZZZZ..",
          "..zZEEZz....",
          "..zZEEZz....",
          "..M....M....",
          "..RRRRRRRR..",
          "..R......R..",
          "..ZZZZZZZZ..",
          "...CC..CC...",
          "...ZZ..ZZ...",
          "..DD....DD..",
          "............",
        },
        {
          "....ZZZZ....",
          "...ZZZZZZ...",
          "..ZZZZZZZZ..",
          "..zZEEZz....",
          "..zZEEZz....",
          "..M....M....",
          "..RRRRRRRR..",
          ".R........R.",
          ".Z........Z.",
          "..ZZZZZZZZ..",
          "..CC..CC....",
          "..DD....DD..",
          "............",
        },
      },
    },
    attack = {
      fps = 10,
      frames = {
        {
          "....ZZZZ....",
          "...ZZZZZZ...",
          "..ZZZZZZZZ..",
          "..zZEEZz....",
          "..zZEEZz....",
          "..M....M....",
          "..RRR..RRR..",
          ".CRR....RRC.",
          ".CZ......ZC.",
          "..ZZZZZZZZ..",
          "..CC..CC....",
          "..DD....DD..",
          "............",
        },
        {
          "....ZZZZ....",
          "...ZZZZZZ...",
          "..ZZZZZZZZ..",
          "..zZEEZz....",
          "..zZEEZz....",
          "..M....M....",
          "..RRR..RRR..",
          ".CRR......RC",
          "..Z......Z..",
          "..ZZZZZZZZ..",
          "..CC..CC....",
          "..DD....DD..",
          "............",
        },
      },
    },
  },
}